# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f074b1e056a8f5810c617baf970edc79"
application_url = "https://mods-gallery-sherman-omissions.trycloudflare.com"
embedded = true
name = "remix-router-folders"
handle = "remix-router-folders"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mods-gallery-sherman-omissions.trycloudflare.com/auth/callback",
  "https://mods-gallery-sherman-omissions.trycloudflare.com/auth/shopify/callback",
  "https://mods-gallery-sherman-omissions.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "qdn-digital.myshopify.com"
automatically_update_urls_on_dev = true
